[project]
name = "billing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.0",
    "requests-auth-aws-sigv4>=0.7",
    "mypy>=1.8.0",
    "autopep8>=2.0.0",
    "types-requests>=2.31.0",
]
