version: 2.1

jobs:
  build-and-lint:
    docker: 
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: make venv
      - run: make install
      - run: make lint

workflows:
  main:
    jobs:
      - build-and-lint
