version: 2.1

jobs:
  build-and-lint:
    docker: 
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: make venv
      - run: make install
      - run: make lint
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo apt-get -y update
      - run: which aws || pip install --user awscli
      - run:
          name: Setup AWS CLI
          command: |
            mkdir -p $HOME/.aws
            echo [default] | tee -a $HOME/.aws/config
            echo region=ap-northeast-1|tee -a $HOME/.aws/config
      - run: make venv
      - run: make install
      - run: make lambda/update

workflows:
  main:
    jobs:
      - build-and-lint
      - deploy:
        requires:
          - build-and-lint
        filters:
          branches:
            only: master
        context:
          - AWS
