version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-lint:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/load-cache:
          dependency-file: requirements-dev.txt
      - python/install-deps
      - python/install-deps:
          dependency-file: requirements-dev.txt
      - python/save-cache
      - python/save-cache:
          dependency-file: requirements-dev.txt
      - run:
          command: make lint
          name: Lint

workflows:
  main:
    jobs:
      - build-and-lint
